// sheet_helpers.js — 翼德 polish:Google Sheets 页内助手(用 Chrome MCP javascript_tool 整段注入一次;页面刷新后要重注)
// 不碰系统剪贴板:文本/格式/图片全部走合成 paste 事件。gid 固定 0 时直接用;多分页改 window.__gid。
window.__gid = window.__gid || '0';
const sleep = ms => new Promise(r => setTimeout(r, ms)); window.__sleep = sleep;
window.__click = el => { const r = el.getBoundingClientRect(); const o = { bubbles: true, cancelable: true, view: window, button: 0, clientX: r.left + r.width / 2, clientY: r.top + r.height / 2 }; ['mouseover', 'mousedown', 'mouseup', 'click'].forEach(t => el.dispatchEvent(new MouseEvent(t, o))); };
// 选格(只在当前激活分页内;切分页要真点 tab)
window.__sel = async r => { location.hash = 'gid=' + window.__gid + '&range=' + r; await sleep(800); document.querySelector('#waffle-rich-text-editor').focus(); return document.querySelector('#t-name-box')?.value; };
// 贴 HTML 表(<td style> 的粗体/底色/字色/colspan/rowspan 生效;<a href> 成超链接;<img> 不生效)
window.__paste = async (range, html) => { location.hash = 'gid=' + window.__gid + '&range=' + range; await sleep(700); const ed = document.querySelector('#waffle-rich-text-editor'); ed.focus(); const dt = new DataTransfer(); dt.setData('text/html', html); dt.setData('text/plain', ''); ed.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })); await sleep(1200); return document.querySelector('#t-name-box')?.value; };
// 图进格子:先 file_upload 把本地图传进 #__yide_file(页内自建 input),再把 File 合成 paste(落浮动图)→ 点溢出菜单「Put image in selected cell」
window.__ensureInput = () => { let inp = document.querySelector('#__yide_file'); if (!inp) { inp = document.createElement('input'); inp.type = 'file'; inp.multiple = true; inp.id = '__yide_file'; inp.setAttribute('aria-label', 'yide image upload input'); inp.style.cssText = 'position:fixed;top:2px;left:600px;z-index:99999;width:220px;height:22px;background:#fff'; document.body.appendChild(inp); } return 'input ready'; };
window.__stashFiles = () => { window.__files = window.__files || {}; for (const f of document.querySelector('#__yide_file').files) window.__files[f.name] = f; return Object.keys(window.__files).length; };
window.__putImg = async (range, file) => { location.hash = 'gid=' + window.__gid + '&range=' + range; await sleep(700); const ed = document.querySelector('#waffle-rich-text-editor'); ed.focus(); const dt = new DataTransfer(); dt.items.add(file); ed.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })); let btn = null; for (let i = 0; i < 40; i++) { await sleep(300); btn = [...document.querySelectorAll('.waffle-overflow-menu-material')].find(e => e.offsetParent); if (btn) break; } if (!btn) return 'no overflow btn'; window.__click(btn); await sleep(500); const item = [...document.querySelectorAll('.goog-menuitem')].find(e => e.offsetParent && /Put image in selected cell/i.test(e.innerText)); if (!item) return 'no menu item'; window.__click(item); await sleep(1200); return 'ok ' + document.querySelector('#t-name-box')?.value; };
// 长任务:后台跑 + 完成标记。⚠ 超时后只准轮询 window.__job,绝不再发会改 selection 的脚本(会贴错位)。
window.__runJob = (items, fn, gap) => { window.__job = { done: false, log: [] }; (async () => { for (const it of items) { try { window.__job.log.push(await fn(it)); } catch (e) { window.__job.log.push('ERR ' + e.message); } await sleep(gap || 1500); } window.__job.done = true; })(); return 'job started ' + items.length; };
// 行高/列宽:先 __sel('5:14') 或 __sel('E:E'),再用 computer 真按 ctrl+shift+\ 开右键菜单,然后调 __resizeDlg(px)
window.__resizeDlg = async px => { const it = [...document.querySelectorAll('.goog-menuitem')].find(e => e.offsetParent && /^Resize/i.test(e.innerText.trim())); if (!it) return 'no resize item'; window.__click(it); await sleep(700); const dlg = [...document.querySelectorAll('.modal-dialog, [role=dialog]')].find(e => e.offsetParent); if (!dlg) return 'no dialog'; const inp = dlg.querySelector('input[type=text], input[type=number], input:not([type=radio])'); const radios = dlg.querySelectorAll('input[type=radio]'); if (radios.length) radios[0].click(); inp.focus(); inp.value = String(px); inp.dispatchEvent(new Event('input', { bubbles: true })); inp.dispatchEvent(new Event('change', { bubbles: true })); await sleep(200); const ok = [...dlg.querySelectorAll('button')].find(b => /^ok$/i.test(b.innerText.trim())); window.__click(ok); ok.click?.(); await sleep(600); return 'ok ' + px; };
// 残留浮动图:__pickFloat() 选中第一张,再用 computer 真按 Delete;重复到返回 'none'
window.__pickFloat = () => { const els = [...document.querySelectorAll('.waffle-borderless-embedded-object-overlay')]; if (!els.length) return 'none'; const e = els[0]; e.scrollIntoView({ block: 'center' }); window.__click(e); return els.length + ' overlays'; };
// 换行/垂直对齐/冻结/合并:选区后用 computer 按 alt+/ 输入 "Wrap text" / "Text align: Middle" / "Text align: Top" / "Freeze up to row 3" / "Unmerge" 再 Return(JS 点子菜单常不生效,真按键稳)
// 读格:__sel('A5') 后取 document.querySelector('#t-formula-bar-input').innerText;输出含 = 或 & 会被工具拦成 [BLOCKED],打印前替换成全角
'helpers ready';
